### ISSUE TITLE
Problem running demo code

### ISSUE THREAD

**Issue by mc19952004** [SheffieldML/multigp#11]
Hi, I was looking to run the demGgToy1 script to get an understanding of the package and what it is doing before then trying it with my own data. I have the package as well as 'GPmat' and 'kern' downloaded and in my path, but when I try to load in the data with '_mapLoadData_', I get the following error. 

_Unrecognized function or variable 'dist2'.
Error in gaussianKernCompute (line 38)
        n2 = dist2(x, x);
Error in multiKernComputeBlock (line 74)
    K = fhandle(arg{:}, X);
Error in multiKernCompute (line 55)
        K(startOne:endOne, startThree:endThree) = multiKernComputeBlock(kern, ...
Error in kernCompute (line 27)
  k = fhandle(kern, x);
Error in mapLoadData (line 577)
            K = kernCompute(kern, XX);
Error in mapLoadData (line 630)
            [XTemp, yTemp, XTestTemp, yTestTemp] = mapLoadData('ggToy');_

I do not seem to have the function '_dist2_' so I am wondering if there are any other dependencies required for me to load in the data? 

Thanks

**Comment by lawrennd** [comment]
HI! It might be that you're missing access to netlab (which has dist2.m in it)

https://github.com/sods/netlab

**Comment by mc19952004** [comment]
Thanks Neil, that has done the trick.
