### ISSUE TITLE
multigpLoadData missing

### ISSUE THREAD

**Issue by ghost** [SheffieldML/multigp#2]
I cannot run most of the demos because the function "multigpLoadData" is missing... How can I get it?

**Comment by mzwiessele** [comment]
Can you please provide a traceback of your error and a reproducing script, which shows when your error shows up?

**Comment by ghost** [comment]
Simply running "demToy1" on multigp/matlab already shows up the error. I have downloaded both the GPmat base library and the multigp extension.

**Comment by lawrennd** [comment]
That example and any example that calls this file should be removed, the
file was replaced with mapLoadData a long time ago. Not by a computer now,
but we'll leave the issue open to remember.

**Comment by raedk** [comment]
In demToy1 I cannot find the toyMultigp1D.mat 
Where is the data stored ?
Thank you

**Comment by lawrennd** [comment]
Example now removed as suggested above.

**Comment by raedk** [comment]
Dear
I am trying to find an example for the sparse approximation in multioutput GP. However, I am not finding matlab file hat can directly run and reproduce the results on the homepage. Please can you tell me what code should I run to reproduce th results in your sparse estimation paper
Best
Raed
