### ISSUE TITLE
Finding the toy 1 datsets

### ISSUE THREAD

**Issue by raedk** [SheffieldML/multigp#3]
Dear,
i am not able to find the 
toyMultigp1DConvExample.mat
spgp1DData.mat
toyMultigp1D
and many others 
please could you help me on locating these files 
Best regards,
raed

**Comment by lawrennd** [comment]
The examples based on these files have been removed. They were included accidentally.

**Comment by raedk** [comment]
Dear
I am trying to find an example for the sparse approximation in multioutput GP. However, I am not finding matlab file hat can directly run and reproduce the results on the homepage. Please can you tell me what code should I run to reproduce th results in your sparse estimation paper
Best
Raed

**Comment by lawrennd** [comment]
You need to be a bit more specific than that. Which home page? Which paper?

**Comment by raedk** [comment]
Hello,
Sorry for the lack of information.
The paper is Computationally Efficient Convolved Multiple Output Gaussian
Processes published in Journal of Machine Learning Research 12 (2011) 1459-1500.
I am trying to reproduce the results in section 6.1 (Toy example)
Thank you 
raed
